//HintName: __TestConsumer_IMyAggregate_2_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace TestConsumer
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal sealed class __TestConsumer_IMyAggregate_2_Aggregate<TKey, TValue> : global::TestConsumer.IMyAggregate<TKey, TValue>
    {
        private readonly global::Autofac.IComponentContext __autofacContext;

        private readonly TKey __Key_value;
        private readonly TValue __Value_value;

        public __TestConsumer_IMyAggregate_2_Aggregate(global::Autofac.IComponentContext context)
        {
            __autofacContext = context;
            __Key_value = (TKey)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(TKey));
            __Value_value = (TValue)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(TValue));
        }

        public TKey Key
        {
            get => __Key_value;
        }

        public TValue Value
        {
            get => __Value_value;
        }
    }
}
