//HintName: __TestConsumer_IMyAggregate_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace TestConsumer
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal sealed class __TestConsumer_IMyAggregate_Aggregate : global::TestConsumer.IMyAggregate
    {
        private readonly global::Autofac.IComponentContext __autofacContext;

        private readonly global::TestConsumer.IDep __Shared_value;
        private readonly global::TestConsumer.IDep __Other_value;

        public __TestConsumer_IMyAggregate_Aggregate(global::Autofac.IComponentContext context)
        {
            __autofacContext = context;
            __Shared_value = (global::TestConsumer.IDep)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IDep));
            __Other_value = (global::TestConsumer.IDep)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IDep));
        }

        public global::TestConsumer.IDep Shared
        {
            get => __Shared_value;
        }

        public global::TestConsumer.IDep Other
        {
            get => __Other_value;
        }
    }
}
