//HintName: __TestConsumer_IMyAggregate_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace TestConsumer
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal sealed class __TestConsumer_IMyAggregate_Aggregate : global::TestConsumer.IMyAggregate
    {
        private readonly global::Autofac.IComponentContext __autofacContext;

        private readonly global::TestConsumer.IMyService __readOnly_value;
        private readonly global::TestConsumer.IMyService __withSetter_value;

        public __TestConsumer_IMyAggregate_Aggregate(global::Autofac.IComponentContext context)
        {
            __autofacContext = context;
            __readOnly_value = (global::TestConsumer.IMyService)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IMyService));
            __withSetter_value = (global::TestConsumer.IMyService)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IMyService));
        }

        public global::TestConsumer.IMyService ReadOnly
        {
            get => __readOnly_value;
        }

        public global::TestConsumer.IMyService WithSetter
        {
            get => __withSetter_value;
            set => throw new global::System.InvalidOperationException("Property setters are not supported on aggregate services.");
        }
    }
}
