//HintName: __TestConsumer_IMyAggregate_1_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace TestConsumer
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal sealed class __TestConsumer_IMyAggregate_1_Aggregate<T> : global::TestConsumer.IMyAggregate<T> where T : class
    {
        private readonly global::Autofac.IComponentContext __autofacContext;

        private readonly T __Item_value;

        public __TestConsumer_IMyAggregate_1_Aggregate(global::Autofac.IComponentContext context)
        {
            __autofacContext = context;
            __Item_value = (T)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(T));
        }

        public T Item
        {
            get => __Item_value;
        }
    }
}
