//HintName: __TestConsumer_IMyAggregate_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace TestConsumer
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal sealed class __TestConsumer_IMyAggregate_Aggregate : global::TestConsumer.IMyAggregate
    {
        private readonly global::Autofac.IComponentContext __autofacContext;


        public __TestConsumer_IMyAggregate_Aggregate(global::Autofac.IComponentContext context)
        {
            __autofacContext = context;
        }

        public global::TestConsumer.IThing<T> Get<T>()
        {
            return (global::TestConsumer.IThing<T>)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IThing<T>));
        }

        public global::TestConsumer.IThing<T> Use<T>(global::TestConsumer.IThing<T> existing)
        {
            var __autofacParameters = new global::Autofac.Core.Parameter[]
            {
                new global::Autofac.TypedParameter(typeof(global::TestConsumer.IThing<T>), existing),
            };
            return (global::TestConsumer.IThing<T>)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IThing<T>), __autofacParameters);
        }
    }
}
