//HintName: __TestConsumer_IMyAggregate_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace TestConsumer
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal sealed class __TestConsumer_IMyAggregate_Aggregate : global::TestConsumer.IMyAggregate
    {
        private readonly global::Autofac.IComponentContext __autofacContext;


        public __TestConsumer_IMyAggregate_Aggregate(global::Autofac.IComponentContext context)
        {
            __autofacContext = context;
        }

        public global::TestConsumer.IMyService GetService()
        {
            return (global::TestConsumer.IMyService)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IMyService));
        }

        public global::TestConsumer.IMyService GetService(int value)
        {
            var __autofacParameters = new global::Autofac.Core.Parameter[]
            {
                new global::Autofac.TypedParameter(typeof(int), value),
            };
            return (global::TestConsumer.IMyService)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IMyService), __autofacParameters);
        }

        public global::TestConsumer.IMyService GetService(global::System.DateTime date, string name)
        {
            var __autofacParameters = new global::Autofac.Core.Parameter[]
            {
                new global::Autofac.TypedParameter(typeof(global::System.DateTime), date),
                new global::Autofac.TypedParameter(typeof(string), name),
            };
            return (global::TestConsumer.IMyService)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IMyService), __autofacParameters);
        }

        public void DoNothing()
        {
            throw new global::System.InvalidOperationException("Methods with a void return type are not supported on aggregate services.");
        }
    }
}
