//HintName: __TestConsumer_IMyAggregate_1_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace TestConsumer
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal sealed class __TestConsumer_IMyAggregate_1_Aggregate<T> : global::TestConsumer.IMyAggregate<T>
    {
        private readonly global::Autofac.IComponentContext __autofacContext;

        private readonly T __item_value;
        private readonly global::TestConsumer.IThing<T> __thing_value;

        public __TestConsumer_IMyAggregate_1_Aggregate(global::Autofac.IComponentContext context)
        {
            __autofacContext = context;
            __item_value = (T)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(T));
            __thing_value = (global::TestConsumer.IThing<T>)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IThing<T>));
        }

        public T Item
        {
            get => __item_value;
        }

        public global::TestConsumer.IThing<T> Thing
        {
            get => __thing_value;
        }
    }
}
