//HintName: __TestConsumer_IMyAggregate_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace TestConsumer
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal sealed class __TestConsumer_IMyAggregate_Aggregate : global::TestConsumer.IMyAggregate
    {
        private readonly global::Autofac.IComponentContext __autofacContext;

        private readonly global::TestConsumer.ISecond __second_value;
        private readonly global::TestConsumer.IFirst __first_value;

        public __TestConsumer_IMyAggregate_Aggregate(global::Autofac.IComponentContext context)
        {
            __autofacContext = context;
            __second_value = (global::TestConsumer.ISecond)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.ISecond));
            __first_value = (global::TestConsumer.IFirst)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::TestConsumer.IFirst));
        }

        public global::TestConsumer.ISecond Second
        {
            get => __second_value;
        }

        public global::TestConsumer.IFirst First
        {
            get => __first_value;
        }
    }
}
