//HintName: GeneratedAggregateServiceRegistrations.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace Autofac.Extras.AggregateService.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal static class GeneratedAggregateServiceModuleInitializer
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Autofac.Extras.AggregateService.GeneratedAggregateServiceRegistry.RegisterOpenGeneric(typeof(global::TestConsumer.IMyAggregate<,>), typeof(global::TestConsumer.__TestConsumer_IMyAggregate_2_Aggregate<,>));
        }
    }
}
