//HintName: GeneratedAggregateServiceRegistrations.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

namespace Autofac.Extras.AggregateService.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
    internal static class GeneratedAggregateServiceModuleInitializer
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Autofac.Extras.AggregateService.GeneratedAggregateServiceRegistry.Register(typeof(global::IGlobalAggregate), static context => new global::__IGlobalAggregate_Aggregate(context));
        }
    }
}
