//HintName: __IGlobalAggregate_Aggregate.g.cs
// <auto-generated/>
#nullable disable
#pragma warning disable

[global::System.CodeDom.Compiler.GeneratedCode("Autofac.Extras.AggregateService.SourceGenerator", null)]
internal sealed class __IGlobalAggregate_Aggregate : global::IGlobalAggregate
{
    private readonly global::Autofac.IComponentContext __autofacContext;

    private readonly global::IGlobalService __Service_value;

    public __IGlobalAggregate_Aggregate(global::Autofac.IComponentContext context)
    {
        __autofacContext = context;
        __Service_value = (global::IGlobalService)global::Autofac.ResolutionExtensions.Resolve(__autofacContext, typeof(global::IGlobalService));
    }

    public global::IGlobalService Service
    {
        get => __Service_value;
    }
}
